# Generated by Django 4.2.10 on 2024-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField()),
                ('available_stock', models.IntegerField()),
            ],
        ),
    ]
